# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvaVNeZX-fYJ7FXppjExywSp9Q6rLPfZ
"""

# Установка Streamlit (выполняется один раз)
!pip install streamlit

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# 1. Настройка интерфейса
st.title("Моделирование дифракции Френеля")
st.sidebar.header("Параметры системы")

# Константы
N = 1024
L_apt = 0.01
wavelength = 550e-9

# Выбор типа апертуры
# --- ОБНОВЛЕННЫЙ ВЫБОР АПЕРТУР ---
choice = st.sidebar.selectbox(
    "Выберите тип апертуры:",
    ('1 - Одна щель', '2 - Две щели', '3 - Прямоугольное отверстие',
     '4 - Крулое отверстие', '5 - Два прямоугольника (наслоение)',
     '6 - Два круга (наслоение)', '7 - Пользовательская формула',
     '8 - Треугольник', '9 - Звездочка', '10 - Две звезды (наслоение)',
     '11 - Три круга (наслоение)')
)

# Сетка координат
coords = np.linspace(-L_apt/2, L_apt/2, N)
X, Y = np.meshgrid(coords, coords)
mask = np.zeros((N, N))

# Вспомогательная функция для генерации звезды
def get_star_mask(X_grid, Y_grid, x0, y0, r_out, r_in):
    dx, dy = X_grid - x0, Y_grid - y0
    r = np.sqrt(dx**2 + dy**2)
    angle = np.arctan2(dy, dx)
    # Математическая формула 5-лучевой звезды
    s = np.abs(np.fmod(angle * 5 / (2 * np.pi) + 0.5, 1.0) - 0.5) * 2
    r_limit = r_out * (r_in / r_out)**s
    return np.where(r < r_limit, 1, 0)

# Логика апертур
if choice.startswith('1'):
    w = st.sidebar.number_input("Ширина щели (мм):", value=0.5) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < 0.005), 1, 0)

elif choice.startswith('2'):
    w = st.sidebar.number_input("Ширина каждой щели (мм):", value=0.05) / 1000
    d = st.sidebar.number_input("Расстояние между центрами (мм):", value=0.25) / 1000
    m1 = np.where((np.abs(X - d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
    m2 = np.where((np.abs(X + d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
    mask = np.maximum(m1, m2)

elif choice.startswith('3'):
    w = st.sidebar.number_input("Ширина прямоугольника (мм):", value=0.5) / 1000
    h = st.sidebar.number_input("Высота прямоугольника (мм):", value=1.0) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < h/2), 1, 0)

elif choice.startswith('4'):
    r = st.sidebar.number_input("Радиус отверстия (мм):", value=0.4) / 1000
    mask = np.where(X**2 + Y**2 < r**2, 1, 0)

elif choice.startswith('8'): # ТРЕУГОЛЬНИК
    a = st.sidebar.number_input("Сторона треугольника (мм):", value=1.5) / 1000
    h = a * np.sqrt(3) / 2
    # Ограничение тремя прямыми для равностороннего треугольника
    c1 = Y < h/2
    c2 = Y > -h/2 + np.sqrt(3) * X
    c3 = Y > -h/2 - np.sqrt(3) * X
    mask = np.where(c1 & c2 & c3, 1, 0)

elif choice.startswith('9'): # ЗВЕЗДОЧКА
    r_out = st.sidebar.number_input("Внешний радиус (мм):", value=0.6) / 1000
    r_in = st.sidebar.number_input("Внутренний радиус (мм):", value=0.25) / 1000
    mask = get_star_mask(X, Y, 0, 0, r_out, r_in)

elif choice.startswith('10'): # ДВЕ ЗВЕЗДЫ
    st.sidebar.markdown("**Введите: x y r_внеш r_внутр**")
    s1_str = st.sidebar.text_input("Звезда 1:", value="-0.4 0 0.3 0.1")
    s2_str = st.sidebar.text_input("Звезда 2:", value="0.4 0 0.3 0.1")
    try:
        p1 = list(map(float, s1_str.split()))
        p2 = list(map(float, s2_str.split()))
        m1 = get_star_mask(X, Y, p1[0]/1000, p1[1]/1000, p1[2]/1000, p1[3]/1000)
        m2 = get_star_mask(X, Y, p2[0]/1000, p2[1]/1000, p2[2]/1000, p2[3]/1000)
        mask = np.maximum(m1, m2)
    except: st.error("Введите 4 числа")

elif choice.startswith('11'): # ТРИ КРУГА
    st.sidebar.markdown("**Введите: x y радиус (мм)**")
    c1_s = st.sidebar.text_input("Круг 1:", value="0 0.5 0.3")
    c2_s = st.sidebar.text_input("Круг 2:", value="-0.5 -0.3 0.3")
    c3_s = st.sidebar.text_input("Круг 3:", value="0.5 -0.3 0.3")
    try:
        p1 = list(map(float, c1_s.split()))
        p2 = list(map(float, c2_s.split()))
        p3 = list(map(float, c3_s.split()))
        m1 = np.where((X - p1[0]/1000)**2 + (Y - p1[1]/1000)**2 < (p1[2]/1000)**2, 1, 0)
        m2 = np.where((X - p2[0]/1000)**2 + (Y - p2[1]/1000)**2 < (p2[2]/1000)**2, 1, 0)
        m3 = np.where((X - p3[0]/1000)**2 + (Y - p3[1]/1000)**2 < (p3[2]/1000)**2, 1, 0)
        mask = np.maximum(m1, np.maximum(m2, m3))
    except: st.error("Введите 3 числа")

elif choice.startswith('5'): # (Остальные блоки оставляем как были...)
    pass # Добавлен pass для исправления IndentationError
    # ... тут твой старый код для прямоугольников ...

# Параметры расстояний
z1 = st.sidebar.number_input("Расстояние от источника до апертуры (z1, м):", value=1.0)
z2 = st.sidebar.number_input("Расстояние от апертуры до экрана (z2, м):", value=1.0)

# 3. Физический расчет
if z1 != 0 and z2 != 0:
    R_eff = 1 / (1/z1 + 1/z2)
    # Фазовый множитель (сферическая волна)
    phase = np.exp(1j * (2 * np.pi / wavelength) * (X**2 + Y**2) / (2 * R_eff))

    # Преобразование Фурье
    field_screen = np.fft.fftshift(np.fft.fft2(mask * phase))
    intensity = np.abs(field_screen)**2
    intensity_viz = np.log10(intensity + 1) # Логарифмическая шкала для видимости

    # Масштаб экрана в мм
    screen_scale_mm = (wavelength * z2 / L_apt) * N * 1000

    # 4. Отрисовка графиков
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

    # Вид апертуры
    ax1.imshow(mask, extent=[-L_apt*500, L_apt*500, -L_apt*500, L_apt*500],
               cmap='gray', origin='lower')
    ax1.set_title("Вид апертуры (мм)")
    ax1.set_xlabel("x, мм")
    ax1.set_ylabel("y, мм")

    # Дифракционная картина
    zoom_area = screen_scale_mm * 0.15 # Коэффициент зума
    center_idx = N // 2

    # КРИТИЧЕСКАЯ ЛОГИКА: коррекция переворота при малых z2
    if z2 < 0.18:
        # В ближней зоне (0.05м)
        display_intensity = intensity_viz.T # Разворачиваем ближнюю зону
        profile_data = intensity[:, center_idx] # Срез поперек новых вертикальных полос
    else:
        # В дальней зоне (1.0м)
        display_intensity = intensity_viz   # В дальней зоне берем как есть
        profile_data = intensity[center_idx, :] # Срез поперек вертикальных полос

    ax2.imshow(display_intensity, cmap='magma', origin='lower',
               extent=[-screen_scale_mm/2, screen_scale_mm/2, -screen_scale_mm/2, screen_scale_mm/2])

    ax2.set_xlim(-zoom_area, zoom_area)
    ax2.set_ylim(-zoom_area, zoom_area)
    ax2.set_title(f"Экран (z2 = {z2} м)")
    ax2.set_xlabel("x, мм")
    ax2.set_ylabel("y, мм")

    st.pyplot(fig)

    # 5. График профиля (сечение)
    fig_line, ax3 = plt.subplots(figsize=(10, 4))
    x_axis = np.linspace(-screen_scale_mm/2, screen_scale_mm/2, N)

    # Защита от деления на ноль, если маска пустая
    max_val = np.max(profile_data)
    if max_val > 0:
        norm_profile = profile_data / max_val
    else:
        norm_profile = profile_data

    ax3.plot(x_axis, norm_profile, color='#1f77b4', lw=1.5)
    ax3.set_xlim(-zoom_area, zoom_area)
    ax3.set_title("Профиль интенсивности (сечение поперек полос)")
    ax3.set_xlabel("Положение на экране (мм)")
    ax3.set_ylabel("I / I_max")
    ax3.grid(True, alpha=0.3)

    st.pyplot(fig_line)
else:
    st.warning("Расстояния z1 и z2 не могут быть равны нулю.")

# Commented out IPython magic to ensure Python compatibility.
# # Сохраняем Streamlit приложение в файл
# %%writefile app.py
# 
# import streamlit as st
# import numpy as np
# import matplotlib.pyplot as plt
# 
# # 1. Настройка интерфейса
# st.title("Моделирование дифракции Френеля")
# st.sidebar.header("Параметры системы")
# 
# # Константы
# N = 1024
# L_apt = 0.01
# wavelength = 550e-9
# 
# # Выбор типа апертуры
# # --- ОБНОВЛЕННЫЙ ВЫБОР АПЕРТУР ---
# choice = st.sidebar.selectbox(
#     "Выберите тип апертуры:",
#     ('1 - Одна щель', '2 - Две щели', '3 - Прямоугольное отверстие',
#      '4 - Крулое отверстие', '5 - Два прямоугольника (наслоение)',
#      '6 - Два круга (наслоение)', '7 - Пользовательская формула',
#      '8 - Треугольник', '9 - Звездочка', '10 - Две звезды (наслоение)',
#      '11 - Три круга (наслоение)')
# )
# 
# # Сетка координат
# coords = np.linspace(-L_apt/2, L_apt/2, N)
# X, Y = np.meshgrid(coords, coords)
# mask = np.zeros((N, N))
# 
# # Вспомогательная функция для генерации звезды
# def get_star_mask(X_grid, Y_grid, x0, y0, r_out, r_in):
#     dx, dy = X_grid - x0, Y_grid - y0
#     r = np.sqrt(dx**2 + dy**2)
#     angle = np.arctan2(dy, dx)
#     # Математическая формула 5-лучевой звезды
#     s = np.abs(np.fmod(angle * 5 / (2 * np.pi) + 0.5, 1.0) - 0.5) * 2
#     r_limit = r_out * (r_in / r_out)**s
#     return np.where(r < r_limit, 1, 0)
# 
# # Логика апертур
# if choice.startswith('1'):
#     w = st.sidebar.number_input("Ширина щели (мм):", value=0.5) / 1000
#     mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < 0.005), 1, 0)
# 
# elif choice.startswith('2'):
#     w = st.sidebar.number_input("Ширина каждой щели (мм):", value=0.05) / 1000
#     d = st.sidebar.number_input("Расстояние между центрами (мм):", value=0.25) / 1000
#     m1 = np.where((np.abs(X - d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
#     m2 = np.where((np.abs(X + d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
#     mask = np.maximum(m1, m2)
# 
# elif choice.startswith('3'):
#     w = st.sidebar.number_input("Ширина прямоугольника (мм):", value=0.5) / 1000
#     h = st.sidebar.number_input("Высота прямоугольника (мм):", value=1.0) / 1000
#     mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < h/2), 1, 0)
# 
# elif choice.startswith('4'):
#     r = st.sidebar.number_input("Радиус отверстия (мм):", value=0.4) / 1000
#     mask = np.where(X**2 + Y**2 < r**2, 1, 0)
# 
# elif choice.startswith('8'): # ТРЕУГОЛЬНИК
#     a = st.sidebar.number_input("Сторона треугольника (мм):", value=1.5) / 1000
#     h = a * np.sqrt(3) / 2
#     # Ограничение тремя прямыми для равностороннего треугольника
#     c1 = Y < h/2
#     c2 = Y > -h/2 + np.sqrt(3) * X
#     c3 = Y > -h/2 - np.sqrt(3) * X
#     mask = np.where(c1 & c2 & c3, 1, 0)
# 
# elif choice.startswith('9'): # ЗВЕЗДОЧКА
#     r_out = st.sidebar.number_input("Внешний радиус (мм):", value=0.6) / 1000
#     r_in = st.sidebar.number_input("Внутренний радиус (мм):", value=0.25) / 1000
#     mask = get_star_mask(X, Y, 0, 0, r_out, r_in)
# 
# elif choice.startswith('10'): # ДВЕ ЗВЕЗДЫ
#     st.sidebar.markdown("**Введите: x y r_внеш r_внутр**")
#     s1_str = st.sidebar.text_input("Звезда 1:", value="-0.4 0 0.3 0.1")
#     s2_str = st.sidebar.text_input("Звезда 2:", value="0.4 0 0.3 0.1")
#     try:
#         p1 = list(map(float, s1_str.split()))
#         p2 = list(map(float, s2_str.split()))
#         m1 = get_star_mask(X, Y, p1[0]/1000, p1[1]/1000, p1[2]/1000, p1[3]/1000)
#         m2 = get_star_mask(X, Y, p2[0]/1000, p2[1]/1000, p2[2]/1000, p2[3]/1000)
#         mask = np.maximum(m1, m2)
#     except: st.error("Введите 4 числа")
# 
# elif choice.startswith('11'): # ТРИ КРУГА
#     st.sidebar.markdown("**Введите: x y радиус (мм)**")
#     c1_s = st.sidebar.text_input("Круг 1:", value="0 0.5 0.3")
#     c2_s = st.sidebar.text_input("Круг 2:", value="-0.5 -0.3 0.3")
#     c3_s = st.sidebar.text_input("Круг 3:", value="0.5 -0.3 0.3")
#     try:
#         p1 = list(map(float, c1_s.split()))
#         p2 = list(map(float, c2_s.split()))
#         p3 = list(map(float, c3_s.split()))
#         m1 = np.where((X - p1[0]/1000)**2 + (Y - p1[1]/1000)**2 < (p1[2]/1000)**2, 1, 0)
#         m2 = np.where((X - p2[0]/1000)**2 + (Y - p2[1]/1000)**2 < (p2[2]/1000)**2, 1, 0)
#         m3 = np.where((X - p3[0]/1000)**2 + (Y - p3[1]/1000)**2 < (p3[2]/1000)**2, 1, 0)
#         mask = np.maximum(m1, np.maximum(m2, m3))
#     except: st.error("Введите 3 числа")
# 
# elif choice.startswith('5'): # (Остальные блоки оставляем как были...)
#     pass # Добавлен pass для исправления IndentationError
#     # ... тут твой старый код для прямоугольников ...
# 
# # Параметры расстояний
# z1 = st.sidebar.number_input("Расстояние от источника до апертуры (z1, м):", value=1.0)
# z2 = st.sidebar.number_input("Расстояние от апертуры до экрана (z2, м):", value=1.0)
# 
# # 3. Физический расчет
# if z1 != 0 and z2 != 0:
#     R_eff = 1 / (1/z1 + 1/z2)
#     # Фазовый множитель (сферическая волна)
#     phase = np.exp(1j * (2 * np.pi / wavelength) * (X**2 + Y**2) / (2 * R_eff))
# 
#     # Преобразование Фурье
#     field_screen = np.fft.fftshift(np.fft.fft2(mask * phase))
#     intensity = np.abs(field_screen)**2
#     intensity_viz = np.log10(intensity + 1) # Логарифмическая шкала для видимости
# 
#     # Масштаб экрана в мм
#     screen_scale_mm = (wavelength * z2 / L_apt) * N * 1000
# 
#     # 4. Отрисовка графиков
#     fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))
# 
#     # Вид апертуры
#     ax1.imshow(mask, extent=[-L_apt*500, L_apt*500, -L_apt*500, L_apt*500],
#                cmap='gray', origin='lower')
#     ax1.set_title("Вид апертуры (мм)")
#     ax1.set_xlabel("x, мм")
#     ax1.set_ylabel("y, мм")
# 
#     # Дифракционная картина
#     zoom_area = screen_scale_mm * 0.15 # Коэффициент зума
#     center_idx = N // 2
# 
#     # КРИТИЧЕСКАЯ ЛОГИКА: коррекция переворота при малых z2
#     if z2 < 0.18:
#         # В ближней зоне (0.05м)
#         display_intensity = intensity_viz.T # Разворачиваем ближнюю зону
#         profile_data = intensity[:, center_idx] # Срез поперек новых вертикальных полос
#     else:
#         # В дальней зоне (1.0м)
#         display_intensity = intensity_viz   # В дальней зоне берем как есть
#         profile_data = intensity[center_idx, :] # Срез поперек вертикальных полос
# 
#     ax2.imshow(display_intensity, cmap='magma', origin='lower',
#                extent=[-screen_scale_mm/2, screen_scale_mm/2, -screen_scale_mm/2, screen_scale_mm/2])
# 
#     ax2.set_xlim(-zoom_area, zoom_area)
#     ax2.set_ylim(-zoom_area, zoom_area)
#     ax2.set_title(f"Экран (z2 = {z2} м)")
#     ax2.set_xlabel("x, мм")
#     ax2.set_ylabel("y, мм")
# 
#     st.pyplot(fig)
# 
#     # 5. График профиля (сечение)
#     fig_line, ax3 = plt.subplots(figsize=(10, 4))
#     x_axis = np.linspace(-screen_scale_mm/2, screen_scale_mm/2, N)
# 
#     # Защита от деления на ноль, если маска пустая
#     max_val = np.max(profile_data)
#     if max_val > 0:
#         norm_profile = profile_data / max_val
#     else:
#         norm_profile = profile_data
# 
#     ax3.plot(x_axis, norm_profile, color='#1f77b4', lw=1.5)
#     ax3.set_xlim(-zoom_area, zoom_area)
#     ax3.set_title("Профиль интенсивности (сечение поперек полос)")
#     ax3.set_xlabel("Положение на экране (мм)")
#     ax3.set_ylabel("I / I_max")
#     ax3.grid(True, alpha=0.3)
# 
#     st.pyplot(fig_line)
# else:
#     st.warning("Расстояния z1 и z2 не могут быть равны нулю.")

"""Теперь, когда приложение сохранено в файл `app.py`, вы можете запустить его с помощью следующей команды. Colab предоставит вам внешний URL-адрес для доступа к приложению Streamlit."""

!streamlit run app.py & npx localtunnel --port 8501