# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvaVNeZX-fYJ7FXppjExywSp9Q6rLPfZ
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# 1. Настройка интерфейса
st.title("Моделирование дифракции Френеля")
st.sidebar.header("Параметры системы")

# Константы
N = 1024
L_apt = 0.01
wavelength = 550e-9

# Выбор типа апертуры
choice = st.sidebar.selectbox(
    "Выберите тип апертуры:",
    ('1 - Одна щель', '2 - Две щели', '3 - Прямоугольное отверстие',
     '4 - Круглое отверстие', '5 - Два прямоугольника (наслоение)',
     '6 - Два круга (наслоение)', '7 - Пользовательская формула')
)

# Сетка координат
coords = np.linspace(-L_apt/2, L_apt/2, N)
X, Y = np.meshgrid(coords, coords)
mask = np.zeros((N, N))

# 2. Логика создания масок (апертур)
if choice.startswith('1'):
    w = st.sidebar.number_input("Ширина щели (мм):", value=0.5) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < 0.005), 1, 0)

elif choice.startswith('2'):
    w = st.sidebar.number_input("Ширина каждой щели (мм):", value=0.05) / 1000
    d = st.sidebar.number_input("Расстояние между центрами (мм):", value=0.25) / 1000
    m1 = np.where((np.abs(X - d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
    m2 = np.where((np.abs(X + d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
    mask = np.maximum(m1, m2)

elif choice.startswith('3'):
    w = st.sidebar.number_input("Ширина прямоугольника (мм):", value=0.5) / 1000
    h = st.sidebar.number_input("Высота прямоугольника (мм):", value=1.0) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < h/2), 1, 0)

elif choice.startswith('4'):
    r = st.sidebar.number_input("Радиус отверстия (мм):", value=0.4) / 1000
    mask = np.where(X**2 + Y**2 < r**2, 1, 0)

elif choice.startswith('5'):
    st.sidebar.markdown("**Введите: x y ширина высота (через пробел)**")
    p1_str = st.sidebar.text_input("Параметры Прямоугольника 1:", value="0 0 4 0.4")
    p2_str = st.sidebar.text_input("Параметры Прямоугольника 2:", value="0 0 0.4 4")
    try:
        p1 = list(map(float, p1_str.split()))
        p2 = list(map(float, p2_str.split()))
        m1 = np.where((np.abs(X - p1[0]/1000) < p1[2]/2000) & (np.abs(Y - p1[1]/1000) < p1[3]/2000), 1, 0)
        m2 = np.where((np.abs(X - p2[0]/1000) < p2[2]/2000) & (np.abs(Y - p2[1]/1000) < p2[3]/2000), 1, 0)
        mask = np.maximum(m1, m2)
    except:
        st.error("Пожалуйста, введите корректные 4 числа через пробел.")

elif choice.startswith('6'):
    st.sidebar.markdown("**Введите: x y радиус (через пробел)**")
    p1_str = st.sidebar.text_input("Параметры Круга 1:", value="-0.3 0 0.2")
    p2_str = st.sidebar.text_input("Параметры Круга 2:", value="0.3 0 0.2")
    try:
        p1 = list(map(float, p1_str.split()))
        p2 = list(map(float, p2_str.split()))
        m1 = np.where((X - p1[0]/1000)**2 + (Y - p1[1]/1000)**2 < (p1[2]/1000)**2, 1, 0)
        m2 = np.where((X - p2[0]/1000)**2 + (Y - p2[1]/1000)**2 < (p2[2]/1000)**2, 1, 0)
        mask = np.maximum(m1, m2)
    except:
        st.error("Пожалуйста, введите корректные 3 числа через пробел.")

elif choice.startswith('7'):
    st.sidebar.markdown("*Пример: (X**2 + Y**2 < 0.001**2)*")
    formula = st.sidebar.text_input("Логическое условие Python:", value="(X**2 + Y**2 < 0.001**2)")
    try:
        mask = np.where(eval(formula), 1, 0)
    except:
        st.error("Ошибка в синтаксисе формулы.")

# Параметры расстояний
z1 = st.sidebar.number_input("Расстояние от источника до апертуры (z1, м):", value=1.0)
z2 = st.sidebar.number_input("Расстояние от апертуры до экрана (z2, м):", value=1.0)

# 3. Физический расчет
if z1 != 0 and z2 != 0:
    R_eff = 1 / (1/z1 + 1/z2)
    # Фазовый множитель (сферическая волна)
    phase = np.exp(1j * (2 * np.pi / wavelength) * (X**2 + Y**2) / (2 * R_eff))

    # Преобразование Фурье
    field_screen = np.fft.fftshift(np.fft.fft2(mask * phase))
    intensity = np.abs(field_screen)**2
    intensity_viz = np.log10(intensity + 1) # Логарифмическая шкала для видимости

    # Масштаб экрана в мм
    screen_scale_mm = (wavelength * z2 / L_apt) * N * 1000

    # 4. Отрисовка графиков
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

    # Вид апертуры
    ax1.imshow(mask, extent=[-L_apt*500, L_apt*500, -L_apt*500, L_apt*500],
               cmap='gray', origin='lower')
    ax1.set_title("Вид апертуры (мм)")
    ax1.set_xlabel("x, мм")
    ax1.set_ylabel("y, мм")

    # Дифракционная картина
    zoom_area = screen_scale_mm * 0.15 # Коэффициент зума
    center_idx = N // 2

    # КРИТИЧЕСКАЯ ЛОГИКА: коррекция переворота при малых z2
    if z2 < 0.18:
        # В ближней зоне (0.05м)
        display_intensity = intensity_viz.T # Разворачиваем ближнюю зону
        profile_data = intensity[:, center_idx] # Срез поперек новых вертикальных полос
    else:
        # В дальней зоне (1.0м)
        display_intensity = intensity_viz   # В дальней зоне берем как есть
        profile_data = intensity[center_idx, :] # Срез поперек вертикальных полос

    ax2.imshow(display_intensity, cmap='magma', origin='lower',
               extent=[-screen_scale_mm/2, screen_scale_mm/2, -screen_scale_mm/2, screen_scale_mm/2])

    ax2.set_xlim(-zoom_area, zoom_area)
    ax2.set_ylim(-zoom_area, zoom_area)
    ax2.set_title(f"Экран (z2 = {z2} м)")
    ax2.set_xlabel("x, мм")
    ax2.set_ylabel("y, мм")

    st.pyplot(fig)

    # 5. График профиля (сечение)
    fig_line, ax3 = plt.subplots(figsize=(10, 4))
    x_axis = np.linspace(-screen_scale_mm/2, screen_scale_mm/2, N)

    # Защита от деления на ноль, если маска пустая
    max_val = np.max(profile_data)
    if max_val > 0:
        norm_profile = profile_data / max_val
    else:
        norm_profile = profile_data

    ax3.plot(x_axis, norm_profile, color='#1f77b4', lw=1.5)
    ax3.set_xlim(-zoom_area, zoom_area)
    ax3.set_title("Профиль интенсивности (сечение поперек полос)")
    ax3.set_xlabel("Положение на экране (мм)")
    ax3.set_ylabel("I / I_max")
    ax3.grid(True, alpha=0.3)

    st.pyplot(fig_line)
else:
    st.warning("Расстояния z1 и z2 не могут быть равны нулю.")