# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvaVNeZX-fYJ7FXppjExywSp9Q6rLPfZ
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# 1. Настройка интерфейса
st.title("Моделирование дифракции Френеля")
st.sidebar.header("Параметры системы")

# Константы
N = 1024
L_apt = 0.01
wavelength = 550e-9

# Выбор типа апертуры
choice = st.sidebar.selectbox(
    "Выберите тип апертуры:",
    ('1 - Одна щель', '2 - Две щели', '3 - Прямоугольное отверстие',
     '4 - Круглое отверстие', '5 - Два прямоугольника',
     '6 - Два круга', '7 - Пользовательская формула')
)

# Сетка координат
coords = np.linspace(-L_apt/2, L_apt/2, N)
X, Y = np.meshgrid(coords, coords)
mask = np.zeros((N, N))

# 2. Логика создания масок (апертур)
if choice.startswith('1'):
    w = st.sidebar.number_input("Ширина щели (мм):", value=0.5) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < 0.005), 1, 0)

elif choice.startswith('2'):
    w = st.sidebar.number_input("Ширина щели (мм):", value=0.05) / 1000
    d = st.sidebar.number_input("Расстояние между центрами (мм):", value=0.2) / 1000
    mask = np.where((np.abs(Y) < 0.005) & ((np.abs(X - d/2) < w/2) | (np.abs(X + d/2) < w/2)), 1, 0)

elif choice.startswith('3'):
    wx = st.sidebar.number_input("Ширина по X (мм):", value=0.5) / 1000
    wy = st.sidebar.number_input("Ширина по Y (мм):", value=0.5) / 1000
    mask = np.where((np.abs(X) < wx/2) & (np.abs(Y) < wy/2), 1, 0)

elif choice.startswith('4'):
    r = st.sidebar.number_input("Радиус отверстия (мм):", value=0.4) / 1000
    mask = np.where(X**2 + Y**2 < r**2, 1, 0)

elif choice.startswith('7'):
    formula = st.sidebar.text_input("Введите формулу (через X и Y):", "np.sin(1000*X)**2")
    try:
        mask = np.where(eval(formula) > 0.5, 1, 0)
    except:
        st.error("Ошибка в формуле!")

# Параметры расстояний
z1 = st.sidebar.number_input("Расстояние от источника до апертуры (z1, м):", value=1.0)
z2 = st.sidebar.number_input("Расстояние от апертуры до экрана (z2, м):", value=1.0)

# 3. Физический расчет
if z1 != 0 and z2 != 0:
    R_eff = 1 / (1/z1 + 1/z2)
    # Фазовый множитель (сферическая волна)
    phase = np.exp(1j * (2 * np.pi / wavelength) * (X**2 + Y**2) / (2 * R_eff))

    # Преобразование Фурье
    field_screen = np.fft.fftshift(np.fft.fft2(mask * phase))
    intensity = np.abs(field_screen)**2
    intensity_viz = np.log10(intensity + 1) # Логарифмическая шкала для видимости

    # Масштаб экрана в мм
    screen_scale_mm = (wavelength * z2 / L_apt) * N * 1000

    # 4. Отрисовка графиков
    # --- ИСПРАВЛЕННАЯ ОТРИСОВКА (ВЕРТИКАЛЬНАЯ ОРИЕНТАЦИЯ) ---
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

    # 1. Апертура (Всегда вертикальная)
    ax1.imshow(mask, extent=[-L_apt*500, L_apt*500, -L_apt*500, L_apt*500],
               cmap='gray', origin='lower')
    ax1.set_title("Вид апертуры (мм)")
    ax1.set_xlabel("x, мм")
    ax1.set_ylabel("y, мм")

    # 2. Экран (Дифракция)
    center_idx = N // 2

    # ЛОГИКА ПОВОРОТА:
    # При z2 > 0.18 (дальняя зона) FFT дает вертикальные полосы сам по себе.
    # При z2 < 0.18 (ближняя зона) алиасинг разворачивает их горизонтально.
    if z2 < 0.18:
        display_intensity = intensity_viz.T # Разворачиваем ближнюю зону
        profile_data = intensity[:, center_idx] # Срез поперек новых вертикальных полос
    else:
        display_intensity = intensity_viz   # В дальней зоне берем как есть
        profile_data = intensity[center_idx, :] # Срез поперек вертикальных полос

    # Масштаб для отрисовки
    zoom_area = screen_scale_mm * 0.15 # Немного увеличим охват для z=1м

    ax2.imshow(display_intensity, cmap='magma', origin='lower',
               extent=[-screen_scale_mm/2, screen_scale_mm/2, -screen_scale_mm/2, screen_scale_mm/2])

    ax2.set_xlim(-zoom_area, zoom_area)
    ax2.set_ylim(-zoom_area, zoom_area)
    ax2.set_title(f"Экран (z2 = {z2} м)")
    ax2.set_xlabel("x, мм")
    ax2.set_ylabel("y, мм")

    st.pyplot(fig)

    # 3. График профиля (Теперь он будет с "зубьями")
    fig_line, ax3 = plt.subplots(figsize=(10, 4))
    x_axis = np.linspace(-screen_scale_mm/2, screen_scale_mm/2, N)

    # Нормировка и отрисовка
    ax3.plot(x_axis, profile_data / np.max(profile_data), color='#1f77b4', lw=1.5)
    ax3.set_xlim(-zoom_area, zoom_area)
    ax3.set_title("Профиль интенсивности (сечение поперек полос)")
    ax3.set_xlabel("Положение на экране (мм)")
    ax3.set_ylabel("I / I_max")
    ax3.grid(True, alpha=0.3)

    st.pyplot(fig_line)