# -*- coding: utf-8 -*-
"""Копия блокнота "Untitled0.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zv7AF6qoc0DVExSh4dqMsQrcIBzqjHq2
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# 1. Настройка интерфейса
st.title("Моделирование дифракции Френеля")
st.sidebar.header("Параметры системы")

# Константы
N = 1024
L_apt = 0.01
wavelength = 550e-9

# Выбор типа апертуры
choice = st.sidebar.selectbox(
    "Выберите тип апертуры:",
    ('1 - Одна щель', '2 - Две щели', '3 - Прямоугольное отверстие',
     '4 - Круглое отверстие', '5 - Два прямоугольника (наслоение)',
     '6 - Два круга (наслоение)', '7 - Пользовательская формула',
     '8 - Треугольник', '9 - Звездочка', '10 - Две звезды (наслоение)',
     '11 - Три круга (наслоение)')
)

# Сетка координат
coords = np.linspace(-L_apt/2, L_apt/2, N)
X, Y = np.meshgrid(coords, coords)
mask = np.zeros((N, N))

# Вспомогательная функция для генерации звезды
def get_star_mask(X_grid, Y_grid, x0, y0, r_out, r_in):
    dx, dy = X_grid - x0, Y_grid - y0
    r = np.sqrt(dx**2 + dy**2)
    # Поворот на -90 градусов, чтобы луч смотрел вверх
    angle = np.arctan2(dy, dx) + np.pi/2
    # Математика 5-лучевой звезды
    s = np.abs(np.fmod(angle * 5 / (2 * np.pi) + 0.5, 1.0) - 0.5) * 2
    r_limit = r_out * (r_in / r_out)**s
    return np.where(r < r_limit, 1, 0)

# Извлекаем номер выбора для точного сравнения
choice_num = choice.split(' ')[0]

# 2. Логика апертур
if choice_num == '1':
    w = st.sidebar.number_input("Ширина щели (мм):", value=0.5) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < 0.005), 1, 0)

elif choice_num == '2':
    w = st.sidebar.number_input("Ширина каждой щели (мм):", value=0.05) / 1000
    d = st.sidebar.number_input("Расстояние между центрами (мм):", value=0.25) / 1000
    m1 = np.where((np.abs(X - d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
    m2 = np.where((np.abs(X + d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
    mask = np.maximum(m1, m2)

elif choice_num == '3':
    w = st.sidebar.number_input("Ширина прямоугольника (мм):", value=0.5) / 1000
    h = st.sidebar.number_input("Высота прямоугольника (мм):", value=1.0) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < h/2), 1, 0)

elif choice_num == '4':
    r = st.sidebar.number_input("Радиус отверстия (мм):", value=0.4) / 1000
    mask = np.where(X**2 + Y**2 < r**2, 1, 0)

elif choice_num == '5': # Два прямоугольника
    w1 = st.sidebar.number_input("Ширина 1 (мм):", value=0.6) / 1000
    h1 = st.sidebar.number_input("Высота 1 (мм):", value=0.2) / 1000
    w2 = st.sidebar.number_input("Ширина 2 (мм):", value=0.2) / 1000
    h2 = st.sidebar.number_input("Высота 2 (мм):", value=0.6) / 1000
    mask = np.maximum(np.where((np.abs(X)<w1/2)&(np.abs(Y)<h1/2),1,0),
                      np.where((np.abs(X)<w2/2)&(np.abs(Y)<h2/2),1,0))

elif choice_num == '6': # Два круга
    r_c = st.sidebar.number_input("Радиус (мм):", value=0.4) / 1000
    d_c = st.sidebar.number_input("Смещение центров (мм):", value=0.5) / 1000
    mask = np.maximum(np.where((X-d_c/2)**2 + Y**2 < r_c**2, 1, 0),
                      np.where((X+d_c/2)**2 + Y**2 < r_c**2, 1, 0))

elif choice_num == '7': # Формула
    f_text = st.sidebar.text_input("Формула (напр. X**2 + Y**2 < 0.001**2):", value="np.abs(X*Y) < 1e-7")
    try: mask = np.where(eval(f_text), 1, 0)
    except: st.error("Ошибка в формуле")

elif choice_num == '8': # ТРЕУГОЛЬНИК (вершиной вверх)
    a = st.sidebar.number_input("Сторона треугольника (мм):", value=1.5) / 1000
    h = a * np.sqrt(3) / 2
    # Ограничение прямыми: основание внизу, вершина вверху
    c1 = Y > -h/3
    c2 = Y < -np.sqrt(3) * X + 2*h/3
    c3 = Y < np.sqrt(3) * X + 2*h/3
    mask = np.where(c1 & c2 & c3, 1, 0)

elif choice_num == '9': # ЗВЕЗДОЧКА
    r_out = st.sidebar.number_input("Внешний радиус (мм):", value=0.8) / 1000
    r_in = st.sidebar.number_input("Внутренний радиус (мм):", value=0.3) / 1000
    mask = get_star_mask(X, Y, 0, 0, r_out, r_in)

elif choice_num == '10': # ДВЕ ЗВЕЗДЫ
    st.sidebar.markdown("Введите через пробел: **x y r_внеш r_внутр**")
    s1 = st.sidebar.text_input("Звезда 1 (мм):", value="-0.6 0 0.4 0.15")
    s2 = st.sidebar.text_input("Звезда 2 (мм):", value="0.6 0 0.4 0.15")
    try:
        p1 = [float(i)/1000 for i in s1.split()]
        p2 = [float(i)/1000 for i in s2.split()]
        mask = np.maximum(get_star_mask(X, Y, p1[0], p1[1], p1[2], p1[3]),
                          get_star_mask(X, Y, p2[0], p2[1], p2[2], p2[3]))
    except: st.warning("Проверьте формат ввода")

elif choice_num == '11': # ТРИ КРУГА
    st.sidebar.markdown("Введите через пробел: **x y радиус**")
    c1 = st.sidebar.text_input("Круг 1 (мм):", value="0 0.6 0.3")
    c2 = st.sidebar.text_input("Круг 2 (мм):", value="-0.6 -0.3 0.3")
    c3 = st.sidebar.text_input("Круг 3 (мм):", value="0.6 -0.3 0.3")
    try:
        p1 = [float(i)/1000 for i in c1.split()]
        p2 = [float(i)/1000 for i in c2.split()]
        p3 = [float(i)/1000 for i in c3.split()]
        m1 = np.where((X-p1[0])**2 + (Y-p1[1])**2 < p1[2]**2, 1, 0)
        m2 = np.where((X-p2[0])**2 + (Y-p2[1])**2 < p2[2]**2, 1, 0)
        m3 = np.where((X-p3[0])**2 + (Y-p3[1])**2 < p3[2]**2, 1, 0)
        mask = np.maximum(m1, np.maximum(m2, m3))
    except: st.warning("Проверьте формат ввода")

# --- Дальше идет физический расчет без изменений ---
z1 = st.sidebar.number_input("Расстояние z1 (м):", value=1.0)
z2 = st.sidebar.number_input("Расстояние z2 (м):", value=1.0)

if z1 != 0 and z2 != 0:
    R_eff = 1 / (1/z1 + 1/z2)
    phase = np.exp(1j * (2 * np.pi / wavelength) * (X**2 + Y**2) / (2 * R_eff))
    field_screen = np.fft.fftshift(np.fft.fft2(mask * phase))
    intensity = np.abs(field_screen)**2
    intensity_viz = np.log10(intensity + 1)
    screen_scale_mm = (wavelength * z2 / L_apt) * N * 1000

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))
    ax1.imshow(mask, extent=[-L_apt*500, L_apt*500, -L_apt*500, L_apt*500], cmap='gray', origin='lower')
    ax1.set_title("Вид апертуры (мм)")

    zoom_area = screen_scale_mm * 0.15
    center_idx = N // 2
    if z2 < 0.18:
        display_intensity, profile_data = intensity_viz.T, intensity[:, center_idx]
    else:
        display_intensity, profile_data = intensity_viz, intensity[center_idx, :]

    ax2.imshow(display_intensity, cmap='magma', origin='lower',
               extent=[-screen_scale_mm/2, screen_scale_mm/2, -screen_scale_mm/2, screen_scale_mm/2])
    ax2.set_xlim(-zoom_area, zoom_area); ax2.set_ylim(-zoom_area, zoom_area)
    ax2.set_title(f"Экран (z2 = {z2} м)")
    st.pyplot(fig)

    fig_line, ax3 = plt.subplots(figsize=(10, 4))
    x_axis = np.linspace(-screen_scale_mm/2, screen_scale_mm/2, N)
    max_val = np.max(profile_data)
    ax3.plot(x_axis, profile_data / max_val if max_val > 0 else profile_data, color='#1f77b4')
    ax3.set_xlim(-zoom_area, zoom_area)
    ax3.set_title("Профиль интенсивности")
    ax3.grid(True, alpha=0.3)
    st.pyplot(fig_line)