# -*- coding: utf-8 -*-
"""Копия блокнота "Untitled0.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zv7AF6qoc0DVExSh4dqMsQrcIBzqjHq2
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# Заголовок сайта
st.title("Моделирование дифракции Френеля")
st.sidebar.header("Настройки апертуры и среды")

N = 4096
L_apt = 0.01
wavelength = 550e-9

# Выпадающий список вместо обычного консольного ввода
choice = st.sidebar.selectbox(
    "Выберите тип апертуры:",
    ('1 - Одна щель', '2 - Две щели', '3 - Прямоугольное отверстие',
     '4 - Круглое отверстие', '5 - Два прямоугольника (наслоение)',
     '6 - Два круга (наслоение)', '7 - Пользовательская формула')
)

coords = np.linspace(-L_apt/2, L_apt/2, N)
X, Y = np.meshgrid(coords, coords)
mask = np.zeros((N, N))

# Логика в зависимости от выбора в меню
if choice.startswith('1'):
    w = st.sidebar.number_input("Ширина щели (мм):", value=0.5) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < 0.005), 1, 0)

elif choice.startswith('2'):
    w = st.sidebar.number_input("Ширина каждой щели (мм):", value=0.05) / 1000
    d = st.sidebar.number_input("Расстояние между центрами (мм):", value=0.25) / 1000
    m1 = np.where((np.abs(X - d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
    m2 = np.where((np.abs(X + d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
    mask = np.maximum(m1, m2)

elif choice.startswith('3'):
    w = st.sidebar.number_input("Ширина прямоугольника (мм):", value=0.5) / 1000
    h = st.sidebar.number_input("Высота прямоугольника (мм):", value=1.0) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < h/2), 1, 0)

elif choice.startswith('4'):
    r = st.sidebar.number_input("Радиус отверстия (мм):", value=0.4) / 1000
    mask = np.where(X**2 + Y**2 < r**2, 1, 0)

elif choice.startswith('5'):
    st.sidebar.markdown("**Введите: x y ширина высота (через пробел)**")
    p1_str = st.sidebar.text_input("Параметры Прямоугольника 1:", value="0 0 4 0.4")
    p2_str = st.sidebar.text_input("Параметры Прямоугольника 2:", value="0 0 0.4 4")
    try:
        p1 = list(map(float, p1_str.split()))
        p2 = list(map(float, p2_str.split()))
        m1 = np.where((np.abs(X - p1[0]/1000) < p1[2]/2000) & (np.abs(Y - p1[1]/1000) < p1[3]/2000), 1, 0)
        m2 = np.where((np.abs(X - p2[0]/1000) < p2[2]/2000) & (np.abs(Y - p2[1]/1000) < p2[3]/2000), 1, 0)
        mask = np.maximum(m1, m2)
    except:
        st.error("Пожалуйста, введите корректные 4 числа через пробел.")

elif choice.startswith('6'):
    st.sidebar.markdown("**Введите: x y радиус (через пробел)**")
    p1_str = st.sidebar.text_input("Параметры Круга 1:", value="-0.3 0 0.2")
    p2_str = st.sidebar.text_input("Параметры Круга 2:", value="0.3 0 0.2")
    try:
        p1 = list(map(float, p1_str.split()))
        p2 = list(map(float, p2_str.split()))
        m1 = np.where((X - p1[0]/1000)**2 + (Y - p1[1]/1000)**2 < (p1[2]/1000)**2, 1, 0)
        m2 = np.where((X - p2[0]/1000)**2 + (Y - p2[1]/1000)**2 < (p2[2]/1000)**2, 1, 0)
        mask = np.maximum(m1, m2)
    except:
        st.error("Пожалуйста, введите корректные 3 числа через пробел.")

elif choice.startswith('7'):
    st.sidebar.markdown("*Пример: (np.abs(np.sin(1500*X)) > 0.8) & (np.abs(Y) < 0.002)*")
    formula = st.sidebar.text_input("Логическое условие Python:", value="(X**2 + Y**2 < 0.001**2)")
    try:
        mask = np.where(eval(formula), 1, 0)
    except:
        st.error("Ошибка в синтаксисе формулы.")

st.sidebar.markdown("---")
z1 = st.sidebar.number_input("Расстояние до апертуры (z1) в метрах:", value=1.0)
z2 = st.sidebar.number_input("Расстояние до экрана (z2) в метрах:", value=1.0)

# Вычисления
k = 2 * np.pi / wavelength
# Защита от деления на ноль
if z1 == 0 or z2 == 0:
    st.warning("Расстояния z1 и z2 не должны быть равны нулю.")
else:
    R_eff = 1 / (1/z1 + 1/z2)
    phase_shift = np.exp(1j * k * (X**2 + Y**2) / (2 * R_eff))


    if choice.startswith('4'): # Если выбрано круглое отверстие
        # r у нас уже определен выше в метрах
        m = (r**2) / (wavelength * R_eff)

        st.sidebar.markdown("---")
        st.sidebar.subheader("Анализ зон Френеля")
        st.sidebar.write(f"Число открытых зон: **{m:.2f}**")

        # Определяем четность/нечетность для вывода подсказки
        m_rounded = int(np.round(m))
        if m_rounded % 2 == 0:
            st.sidebar.info(f"Центральное пятно должно быть **ТЕМНЫМ** (m ≈ {m_rounded})")
        else:
            st.sidebar.info(f"Центральное пятно должно быть **СВЕТЛЫМ** (m ≈ {m_rounded})")


    field_screen = np.fft.fftshift(np.fft.fft2(mask * phase_shift))
    intensity = np.abs(field_screen)**2
    intensity_viz = np.log10(intensity + 1)

    screen_scale_mm = (wavelength * z2 / L_apt) * N * 1000

    # Отрисовка графиков
    # --- ИСПРАВЛЕННЫЙ БЛОК ОТРИСОВКИ ---
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

    # 1. Апертура
    # Добавляем origin='lower', чтобы ось Y росла вверх, а не вниз
    ax1.imshow(mask, extent=[-L_apt*500, L_apt*500, -L_apt*500, L_apt*500],
               cmap='gray', origin='lower')
    ax1.set_title("Вид апертуры (мм)")
    ax1.set_xlabel("x, мм")
    ax1.set_ylabel("y, мм")

    # 2. Экран
    zoo_mpl = 0.1
    zoom_area = screen_scale_mm * zoo_mpl

    # КРИТИЧЕСКОЕ ИЗМЕНЕНИЕ: Транспонируем матрицу intensity_viz.T
    # Это поменяет местами строки и столбцы, развернув картину на 90 градусов
    ax2.imshow(intensity_viz.T, cmap='magma', origin='lower',
               extent=[-screen_scale_mm/2, screen_scale_mm/2, -screen_scale_mm/2, screen_scale_mm/2])

    ax2.set_xlim(-zoom_area, zoom_area)
    ax2.set_ylim(-zoom_area, zoom_area)
    ax2.set_title(f"Дифракция (Экран на {z2} м)")
    ax2.set_xlabel("x на экране, мм")
    ax2.set_ylabel("y на экране, мм")

    plt.tight_layout()
    st.pyplot(fig)

    # 3. Профиль интенсивности
    fig_line, ax3 = plt.subplots(figsize=(10, 3))
    center_idx = N // 2

    # Срез интенсивности должен соответствовать направлению дифракции
    # После транспонирования для вертикальной щели используем срез по центру
    profile = intensity[:, center_idx]

    x_axis = np.linspace(-screen_scale_mm/2, screen_scale_mm/2, N)
    ax3.plot(x_axis, profile / np.max(profile), color='#1f77b4')
    ax3.set_xlim(-zoom_area, zoom_area)
    ax3.set_title("Профиль интенсивности (центральное сечение)")
    ax3.set_xlabel("Положение на экране (мм)")
    ax3.set_ylabel("I / I_max")
    ax3.grid(True, alpha=0.3)

    st.pyplot(fig_line)


    # 2. ДОБАВЛЕНИЕ ГРАФИК ПРОФИЛЯ
    fig_line, ax3 = plt.subplots(figsize=(10, 3))

    center_idx = N // 2
    profile = intensity[center_idx, :] # Срез интенсивности по центру
    x_axis = np.linspace(-screen_scale_mm/2, screen_scale_mm/2, N)

    # Рисуем линию, нормируя её для удобства (от 0 до 1)
    ax3.plot(x_axis, profile / np.max(profile), color='#1f77b4')
    ax3.set_xlim(-zoom_area, zoom_area) # Тот же масштаб, что на 2D картинке
    ax3.set_title("Профиль интенсивности (центральное сечение)")
    ax3.set_xlabel("Положение на экране (мм)")
    ax3.set_ylabel("I / I_max")
    ax3.grid(True, alpha=0.3)

    # Вывод второй график отдельно ниже
    st.pyplot(fig_line)# -*- coding: utf-8 -*-
"""Копия блокнота "Untitled0.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zv7AF6qoc0DVExSh4dqMsQrcIBzqjHq2
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# Заголовок сайта
st.title("Моделирование дифракции Френеля")
st.sidebar.header("Настройки апертуры и среды")

N = 1024
L_apt = 0.01
wavelength = 550e-9

# Выпадающий список вместо обычного консольного ввода
choice = st.sidebar.selectbox(
    "Выберите тип апертуры:",
    ('1 - Одна щель', '2 - Две щели', '3 - Прямоугольное отверстие',
     '4 - Круглое отверстие', '5 - Два прямоугольника (наслоение)',
     '6 - Два круга (наслоение)', '7 - Пользовательская формула')
)

coords = np.linspace(-L_apt/2, L_apt/2, N)
X, Y = np.meshgrid(coords, coords)
mask = np.zeros((N, N))

# Логика в зависимости от выбора в меню
if choice.startswith('1'):
    w = st.sidebar.number_input("Ширина щели (мм):", value=0.5) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < 0.005), 1, 0)

elif choice.startswith('2'):
    w = st.sidebar.number_input("Ширина каждой щели (мм):", value=0.05) / 1000
    d = st.sidebar.number_input("Расстояние между центрами (мм):", value=0.25) / 1000
    m1 = np.where((np.abs(X - d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
    m2 = np.where((np.abs(X + d/2) < w/2) & (np.abs(Y) < 0.005), 1, 0)
    mask = np.maximum(m1, m2)

elif choice.startswith('3'):
    w = st.sidebar.number_input("Ширина прямоугольника (мм):", value=0.5) / 1000
    h = st.sidebar.number_input("Высота прямоугольника (мм):", value=1.0) / 1000
    mask = np.where((np.abs(X) < w/2) & (np.abs(Y) < h/2), 1, 0)

elif choice.startswith('4'):
    r = st.sidebar.number_input("Радиус отверстия (мм):", value=0.4) / 1000
    mask = np.where(X**2 + Y**2 < r**2, 1, 0)

elif choice.startswith('5'):
    st.sidebar.markdown("**Введите: x y ширина высота (через пробел)**")
    p1_str = st.sidebar.text_input("Параметры Прямоугольника 1:", value="0 0 4 0.4")
    p2_str = st.sidebar.text_input("Параметры Прямоугольника 2:", value="0 0 0.4 4")
    try:
        p1 = list(map(float, p1_str.split()))
        p2 = list(map(float, p2_str.split()))
        m1 = np.where((np.abs(X - p1[0]/1000) < p1[2]/2000) & (np.abs(Y - p1[1]/1000) < p1[3]/2000), 1, 0)
        m2 = np.where((np.abs(X - p2[0]/1000) < p2[2]/2000) & (np.abs(Y - p2[1]/1000) < p2[3]/2000), 1, 0)
        mask = np.maximum(m1, m2)
    except:
        st.error("Пожалуйста, введите корректные 4 числа через пробел.")

elif choice.startswith('6'):
    st.sidebar.markdown("**Введите: x y радиус (через пробел)**")
    p1_str = st.sidebar.text_input("Параметры Круга 1:", value="-0.3 0 0.2")
    p2_str = st.sidebar.text_input("Параметры Круга 2:", value="0.3 0 0.2")
    try:
        p1 = list(map(float, p1_str.split()))
        p2 = list(map(float, p2_str.split()))
        m1 = np.where((X - p1[0]/1000)**2 + (Y - p1[1]/1000)**2 < (p1[2]/1000)**2, 1, 0)
        m2 = np.where((X - p2[0]/1000)**2 + (Y - p2[1]/1000)**2 < (p2[2]/1000)**2, 1, 0)
        mask = np.maximum(m1, m2)
    except:
        st.error("Пожалуйста, введите корректные 3 числа через пробел.")

elif choice.startswith('7'):
    st.sidebar.markdown("*Пример: (np.abs(np.sin(1500*X)) > 0.8) & (np.abs(Y) < 0.002)*")
    formula = st.sidebar.text_input("Логическое условие Python:", value="(X**2 + Y**2 < 0.001**2)")
    try:
        mask = np.where(eval(formula), 1, 0)
    except:
        st.error("Ошибка в синтаксисе формулы.")

st.sidebar.markdown("---")
z1 = st.sidebar.number_input("Расстояние до апертуры (z1) в метрах:", value=1.0)
z2 = st.sidebar.number_input("Расстояние до экрана (z2) в метрах:", value=1.0)

# Вычисления
k = 2 * np.pi / wavelength
# Защита от деления на ноль
if z1 == 0 or z2 == 0:
    st.warning("Расстояния z1 и z2 не должны быть равны нулю.")
else:
    R_eff = 1 / (1/z1 + 1/z2)
    phase_shift = np.exp(1j * k * (X**2 + Y**2) / (2 * R_eff))

    field_screen = np.fft.fftshift(np.fft.fft2(mask * phase_shift))
    intensity = np.abs(field_screen)**2
    intensity_viz = np.log10(intensity + 1)

    screen_scale_mm = (wavelength * z2 / L_apt) * N * 1000

    # Отрисовка графиков
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

    # Апертура
    ax1.imshow(mask, extent=[-L_apt*500, L_apt*500, -L_apt*500, L_apt*500], cmap='gray')
    ax1.set_title("Вид апертуры (мм)")
    ax1.set_xlabel("x, мм")
    ax1.set_ylabel("y, мм")

    # Экран
    zoo_mpl = 0.1
    zoom_area = screen_scale_mm * zoo_mpl
    ax2.imshow(intensity_viz, cmap='magma', extent=[-screen_scale_mm/2, screen_scale_mm/2, -screen_scale_mm/2, screen_scale_mm/2])
    ax2.set_xlim(-zoom_area, zoom_area)
    ax2.set_ylim(-zoom_area, zoom_area)
    ax2.set_title(f"Дифракция (Экран на {z2} м)")
    ax2.set_xlabel("x на экране, мм")
    ax2.set_ylabel("y на экране, мм")

    plt.tight_layout()

    # Передаем фигуру в streamlit
    st.pyplot(fig)


    # 2. ДОБАВЛЯЕМ ГРАФИК ПРОФИЛЯ (КАК У ОДНОГРУППНИКА)
    fig_line, ax3 = plt.subplots(figsize=(10, 3))

    center_idx = N // 2
    profile = intensity[center_idx, :] # Срез интенсивности по центру
    x_axis = np.linspace(-screen_scale_mm/2, screen_scale_mm/2, N)

    # Рисуем линию, нормируя её для удобства (от 0 до 1)
    ax3.plot(x_axis, profile / np.max(profile), color='#1f77b4')
    ax3.set_xlim(-zoom_area, zoom_area) # Тот же масштаб, что на 2D картинке
    ax3.set_title("Профиль интенсивности (центральное сечение)")
    ax3.set_xlabel("Положение на экране (мм)")
    ax3.set_ylabel("I / I_max")
    ax3.grid(True, alpha=0.3)

    # Выводим второй график отдельно ниже
    st.pyplot(fig_line)